/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GardenStats = IDL.Record({
  'totalBlooms' : IDL.Nat,
  'totalWaters' : IDL.Nat,
});
export const Plant = IDL.Record({
  'growthStage' : IDL.Nat,
  'waterCount' : IDL.Nat,
  'seedType' : IDL.Text,
});
export const Garden = IDL.Record({
  'stats' : GardenStats,
  'plots' : IDL.Vec(IDL.Opt(Plant)),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearPlot' : IDL.Func([IDL.Nat], [], []),
  'getAllGardens' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, Garden))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGarden' : IDL.Func([], [Garden], ['query']),
  'getStats' : IDL.Func([], [GardenStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'plantSeed' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'waterPlant' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GardenStats = IDL.Record({
    'totalBlooms' : IDL.Nat,
    'totalWaters' : IDL.Nat,
  });
  const Plant = IDL.Record({
    'growthStage' : IDL.Nat,
    'waterCount' : IDL.Nat,
    'seedType' : IDL.Text,
  });
  const Garden = IDL.Record({
    'stats' : GardenStats,
    'plots' : IDL.Vec(IDL.Opt(Plant)),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearPlot' : IDL.Func([IDL.Nat], [], []),
    'getAllGardens' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Garden))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGarden' : IDL.Func([], [Garden], ['query']),
    'getStats' : IDL.Func([], [GardenStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'plantSeed' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'waterPlant' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };